name: Testing the Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install -r hemalatha/requirements.txt

    - name: Check if classifier.pkl exists
      run: ls -l hemalatha/

    - name: Run Test Cases
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)/hemalatha
        pytest hemalatha/test.py
